### ISSUE TITLE
Example run from the readme fails because the TL plugin requires google cloud key.

### ISSUE THREAD

**Issue by C0rn3j** [uniborg/uniborg#3]
Example run from the readme fails because the TL plugin requires google cloud key.

```python
# python stdborg.py
Traceback (most recent call last):
  File "/root/uniborg/stdborg.py", line 11, in <module>
    borg = Uniborg("stdborg", plugin_path="stdplugins", connection_retries=None)
  File "/root/uniborg/uniborg/uniborg.py", line 43, in __init__
    self.loop.run_until_complete(self._async_init(bot_token=bot_token))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/uniborg/uniborg/uniborg.py", line 55, in _async_init
    await self.load_plugin_from_file(p)
  File "/root/uniborg/uniborg/uniborg.py", line 72, in load_plugin_from_file
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/uniborg/stdplugins/tl.py", line 25, in <module>
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/lib/python3.10/site-packages/google/oauth2/service_account.py", line 237, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/lib/python3.10/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'google_cloud_key.json'
```

**Comment by 9ary** [comment]
Ah yes, perhaps that should be documented. uniborg is primarily developed for personal use so I don't always take the time to do that. The Google Cloud key is required because that plugin uses the Translate and TTS APIs.

**Comment by C0rn3j** [comment]
If you're already editing the readme, it'd also be nice to show some example plugin use, for example just sending `.info` in a reply to demonstrate the `info` plugin, took me a while to understand how things work.

Still a bit confused about the two splits between std and bot directories/files too.

**Comment by 9ary** [comment]
> If you're already editing the readme, it'd also be nice to show some example plugin use, for example just sending `.info` in a reply to demonstrate the `info` plugin, took me a while to understand how things work.

It'd be nice to document the plugins a bit more but it's not really a priority at the moment.
 
> Still a bit confused about the two splits between std and bot directories/files too.

uniborg can run either as a userbot under your own account ("borg mode") or as a regular bot that you can add to groups and probably channels. The botplugins directory contains plugins that have been adapted to run in bot mode.
